{{
    config(
        materialized = 'view'
    )
}}

WITH source AS (
  SELECT
    BAN_INVOICE_ID,
    BAN_INVOICE_REF,
    BAN_VENDOR_CODE,
    BAN_VENDOR_DESC,
    BAN_INV_DATE,
    BAN_PAY_DATE,
    BAN_AMOUNT,
    BAN_CURR,
    BAN_PAY_TERMS,
    BAN_PO_REF,
    BAN_LINE_DESC,
    BAN_GL_CODE,
    BAN_COST_CTR,
    BAN_STATUS,
    BAN_CREATED,
    BAN_COMPANY
  FROM {{ source('ap_bronze', 'BRONZE_BAAN_AP_INVOICES') }}
),

renamed AS (
  SELECT
    'BAAN' || '-' || BAN_INVOICE_ID AS INVOICE_KEY,
    'BAAN' AS SOURCE_SYSTEM,
    BAN_INVOICE_ID AS SOURCE_INVOICE_ID,
    BAN_INVOICE_REF AS INVOICE_NUMBER,
    BAN_VENDOR_CODE AS VENDOR_ID,
    TRIM(BAN_VENDOR_DESC) AS VENDOR_NAME,
    BAN_INV_DATE AS INVOICE_DATE,
    BAN_PAY_DATE AS DUE_DATE,
    BAN_AMOUNT::NUMBER(18,2) AS INVOICE_AMOUNT,
    BAN_CURR AS CURRENCY_CODE,
    BAN_PAY_TERMS AS SOURCE_PAYMENT_TERMS,
    BAN_PO_REF AS PO_NUMBER,
    BAN_LINE_DESC AS LINE_DESCRIPTION,
    BAN_GL_CODE AS GL_ACCOUNT,
    BAN_COST_CTR AS SOURCE_COST_CENTER,
    BAN_STATUS AS SOURCE_APPROVAL_STATUS,
    BAN_CREATED AS CREATED_AT,
    BAN_COMPANY AS SOURCE_ORG_CODE,
    NULL AS SOURCE_DOCUMENT_TYPE,
    NULL AS SOURCE_ENTRY_METHOD
  FROM source
),

logic AS (
  SELECT
    INVOICE_KEY,
    SOURCE_SYSTEM,
    SOURCE_INVOICE_ID,
    INVOICE_NUMBER,
    VENDOR_ID,
    VENDOR_NAME,
    INVOICE_DATE,
    DUE_DATE,
    INVOICE_AMOUNT,
    CURRENCY_CODE,
    CASE SOURCE_PAYMENT_TERMS
      WHEN 'N30' THEN 'NET30'
      WHEN 'N60' THEN 'NET60'
      ELSE NULL
    END AS PAYMENT_TERMS,
    PO_NUMBER,
    LINE_DESCRIPTION,
    GL_ACCOUNT,
    CASE
      WHEN POSITION('-' IN SOURCE_COST_CENTER) > 0
        THEN SUBSTRING(SOURCE_COST_CENTER, POSITION('-' IN SOURCE_COST_CENTER) + 1)
      ELSE SOURCE_COST_CENTER
    END AS COST_CENTER_OR_DEPT,
    CASE SOURCE_APPROVAL_STATUS
      WHEN 'POSTED' THEN 'APPROVED'
      WHEN 'APPROVED' THEN 'APPROVED'
      WHEN 'PENDING' THEN 'PENDING'
      ELSE NULL
    END AS APPROVAL_STATUS,
    CREATED_AT,
    SOURCE_ORG_CODE,
    SOURCE_DOCUMENT_TYPE,
    SOURCE_ENTRY_METHOD
  FROM renamed
)

SELECT
  INVOICE_KEY,
  SOURCE_SYSTEM,
  SOURCE_INVOICE_ID,
  INVOICE_NUMBER,
  VENDOR_ID,
  VENDOR_NAME,
  INVOICE_DATE,
  DUE_DATE,
  INVOICE_AMOUNT,
  CURRENCY_CODE,
  PAYMENT_TERMS,
  PO_NUMBER,
  LINE_DESCRIPTION,
  GL_ACCOUNT,
  COST_CENTER_OR_DEPT,
  APPROVAL_STATUS,
  CREATED_AT,
  SOURCE_ORG_CODE,
  SOURCE_DOCUMENT_TYPE,
  SOURCE_ENTRY_METHOD
FROM logic