{{
    config(
        materialized = 'view'
    )
}}

WITH source AS (
  SELECT
    INVOICE_ID,
    INVOICE_NUMBER,
    VENDOR_ID,
    VENDOR_NAME,
    INVOICE_DATE,
    DUE_DATE,
    INVOICE_AMOUNT,
    CURRENCY_CODE,
    PAYMENT_TERMS,
    PO_NUMBER,
    LINE_DESCRIPTION,
    GL_ACCOUNT,
    COST_CENTER,
    APPROVAL_STATUS,
    CREATED_AT,
    SAP_COMPANY_CODE,
    SAP_DOCUMENT_TYPE
  FROM {{ source('ap_bronze', 'BRONZE_SAP_AP_INVOICES') }}
),

renamed AS (
  SELECT
    'SAP' || '-' || INVOICE_ID AS INVOICE_KEY,
    'SAP' AS SOURCE_SYSTEM,
    INVOICE_ID AS SOURCE_INVOICE_ID,
    INVOICE_NUMBER,
    VENDOR_ID,
    TRIM(VENDOR_NAME) AS VENDOR_NAME,
    INVOICE_DATE::DATE AS INVOICE_DATE,
    DUE_DATE::DATE AS DUE_DATE,
    INVOICE_AMOUNT::NUMBER(18,2) AS INVOICE_AMOUNT,
    CURRENCY_CODE,
    PAYMENT_TERMS AS SOURCE_PAYMENT_TERMS,
    PO_NUMBER,
    LINE_DESCRIPTION,
    GL_ACCOUNT,
    COST_CENTER AS SOURCE_COST_CENTER,
    APPROVAL_STATUS AS SOURCE_APPROVAL_STATUS,
    CREATED_AT::TIMESTAMP_NTZ AS CREATED_AT,
    SAP_COMPANY_CODE AS SOURCE_ORG_CODE,
    SAP_DOCUMENT_TYPE AS SOURCE_DOCUMENT_TYPE,
    NULL AS SOURCE_ENTRY_METHOD
  FROM source
),

logic AS (
  SELECT
    INVOICE_KEY,
    SOURCE_SYSTEM,
    SOURCE_INVOICE_ID,
    INVOICE_NUMBER,
    VENDOR_ID,
    VENDOR_NAME,
    INVOICE_DATE,
    DUE_DATE,
    INVOICE_AMOUNT,
    CURRENCY_CODE,
    CASE
      WHEN SOURCE_PAYMENT_TERMS = 'NET30' THEN 'NET30'
      WHEN SOURCE_PAYMENT_TERMS = 'NET60' THEN 'NET60'
      ELSE NULL
    END AS PAYMENT_TERMS,
    PO_NUMBER,
    LINE_DESCRIPTION,
    GL_ACCOUNT,
    CASE
      WHEN POSITION('-' IN SOURCE_COST_CENTER) > 0
        THEN SUBSTRING(SOURCE_COST_CENTER, POSITION('-' IN SOURCE_COST_CENTER) + 1)
      ELSE SOURCE_COST_CENTER
    END AS COST_CENTER_OR_DEPT,
    CASE
      WHEN SOURCE_APPROVAL_STATUS = 'APPROVED' THEN 'APPROVED'
      WHEN SOURCE_APPROVAL_STATUS = 'PENDING' THEN 'PENDING'
      ELSE NULL
    END AS APPROVAL_STATUS,
    CREATED_AT,
    SOURCE_ORG_CODE,
    SOURCE_DOCUMENT_TYPE,
    SOURCE_ENTRY_METHOD
  FROM renamed
)

SELECT
  INVOICE_KEY,
  SOURCE_SYSTEM,
  SOURCE_INVOICE_ID,
  INVOICE_NUMBER,
  VENDOR_ID,
  VENDOR_NAME,
  INVOICE_DATE,
  DUE_DATE,
  INVOICE_AMOUNT,
  CURRENCY_CODE,
  PAYMENT_TERMS,
  PO_NUMBER,
  LINE_DESCRIPTION,
  GL_ACCOUNT,
  COST_CENTER_OR_DEPT,
  APPROVAL_STATUS,
  CREATED_AT,
  SOURCE_ORG_CODE,
  SOURCE_DOCUMENT_TYPE,
  SOURCE_ENTRY_METHOD
FROM logic