{{
    config(
        materialized = 'view'
    )
}}

WITH source AS (
  SELECT
    INV_ID,
    INV_NUM,
    SUPPLIER_ID,
    SUPPLIER_NAME,
    INV_DATE,
    PAYMENT_DUE_DATE,
    TOTAL_AMOUNT,
    CURRENCY,
    TERMS_CODE,
    PURCHASE_ORDER,
    DESCRIPTION,
    ACCOUNT_CODE,
    DEPT_CODE,
    STATUS,
    CREATION_DATE,
    ORACLE_ORG_ID,
    ORACLE_SOURCE
  FROM {{ source('ap_bronze', 'BRONZE_ORACLE_AP_INVOICES') }}
),

renamed AS (
  SELECT
    'ORACLE' || '-' || INV_ID AS INVOICE_KEY,
    'ORACLE' AS SOURCE_SYSTEM,
    INV_ID AS SOURCE_INVOICE_ID,
    INV_NUM AS INVOICE_NUMBER,
    SUPPLIER_ID AS VENDOR_ID,
    TRIM(SUPPLIER_NAME) AS VENDOR_NAME,
    INV_DATE AS INVOICE_DATE,
    PAYMENT_DUE_DATE AS DUE_DATE,
    TOTAL_AMOUNT::NUMBER(18,2) AS INVOICE_AMOUNT,
    CURRENCY AS CURRENCY_CODE,
    TERMS_CODE AS SOURCE_TERMS_CODE,
    PURCHASE_ORDER AS PO_NUMBER,
    DESCRIPTION AS LINE_DESCRIPTION,
    ACCOUNT_CODE AS GL_ACCOUNT,
    DEPT_CODE AS SOURCE_DEPT_CODE,
    STATUS AS SOURCE_STATUS,
    CREATION_DATE AS CREATED_AT,
    ORACLE_ORG_ID AS SOURCE_ORG_CODE,
    NULL AS SOURCE_DOCUMENT_TYPE,
    ORACLE_SOURCE AS SOURCE_ENTRY_METHOD
  FROM source
),

logic AS (
  SELECT
    INVOICE_KEY,
    SOURCE_SYSTEM,
    SOURCE_INVOICE_ID,
    INVOICE_NUMBER,
    VENDOR_ID,
    VENDOR_NAME,
    INVOICE_DATE,
    DUE_DATE,
    INVOICE_AMOUNT,
    CURRENCY_CODE,
    CASE SOURCE_TERMS_CODE
      WHEN 'N30' THEN 'NET30'
      WHEN 'N60' THEN 'NET60'
      ELSE NULL
    END AS PAYMENT_TERMS,
    PO_NUMBER,
    LINE_DESCRIPTION,
    GL_ACCOUNT,
    CASE
      WHEN POSITION('-' IN SOURCE_DEPT_CODE) > 0
        THEN SUBSTRING(SOURCE_DEPT_CODE, POSITION('-' IN SOURCE_DEPT_CODE) + 1)
      ELSE SOURCE_DEPT_CODE
    END AS COST_CENTER_OR_DEPT,
    CASE SOURCE_STATUS
      WHEN 'VALIDATED' THEN 'APPROVED'
      WHEN 'APPROVED' THEN 'APPROVED'
      WHEN 'PENDING' THEN 'PENDING'
      ELSE NULL
    END AS APPROVAL_STATUS,
    CREATED_AT,
    SOURCE_ORG_CODE,
    SOURCE_DOCUMENT_TYPE,
    SOURCE_ENTRY_METHOD
  FROM renamed
)

SELECT
  INVOICE_KEY,
  SOURCE_SYSTEM,
  SOURCE_INVOICE_ID,
  INVOICE_NUMBER,
  VENDOR_ID,
  VENDOR_NAME,
  INVOICE_DATE,
  DUE_DATE,
  INVOICE_AMOUNT,
  CURRENCY_CODE,
  PAYMENT_TERMS,
  PO_NUMBER,
  LINE_DESCRIPTION,
  GL_ACCOUNT,
  COST_CENTER_OR_DEPT,
  APPROVAL_STATUS,
  CREATED_AT,
  SOURCE_ORG_CODE,
  SOURCE_DOCUMENT_TYPE,
  SOURCE_ENTRY_METHOD
FROM logic